name: Main CI/CD
on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  version-check:
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
  release:
    if: needs.version-check.outputs.check == 'true'
    needs: [test, version-check]
    uses: ./.github/workflows/release.yaml