name: Main CI/CD
on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: EndBug/version-check@v1
      - uses: ./.github/workflows/release.yaml