name: Main CI/CD
on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/version-check@v1
  release:
    needs: [test, version-check]
    uses: ./.github/workflows/release.yaml